### ISSUE TITLE
shellscript strings are not highlighted inside a `for ((` loop

### ISSUE THREAD

**Issue by lilyball** [PROxZIMA/sweet-dracula#2]
I just filed this upstream at https://github.com/dracula/visual-studio-code/issues/212 but it affects Sweet Dracula too. If I'm writing shellscript, strings inside the body of a `for ((` loop don't get highlighted.

<img width="583" alt="screenshot showing highlighting of strings in shell for loops" src="https://user-images.githubusercontent.com/714/157542982-0b166269-a60d-4dde-ac49-b22d3dfa2896.png">

This appears to be due to the following rule:

```json
{
    "name": "Shell foreground resets",
    "scope": [
        "meta.scope.for-loop.shell punctuation.definition.string.begin",
        "meta.scope.for-loop.shell punctuation.definition.string.end",
        "meta.scope.for-loop.shell string"
    ],
    "settings": {
        "foreground": "#F8F8F2"
    }
}
```

This looks like it was adapted from a similar rule in Dracula (except you appear to have split that one rule into multiple separate "foreground resets" rules).

There are no other rules that match `meta.scope.for-loop.shell` and so there should be no need to reset anything. And especially not back to the base foreground color, as strings are supposed to be colored differently.

**Comment by PROxZIMA** [comment]
Understood. Mentioned code is more or less redundant.
